name: Matrix Demo
on: push
jobs:
  builds:
    strategy:
      matrix:
        node-versions: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions }}
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
