name: Reusable Deploy
on: workflow_call # allow this workflow to be called by other
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: echo "Deploying & Uploading...."
